drop table if exsists article CASCADE;
create table article
    {
    contentId bigint generated by default as identity,
    email varchar(255),
    title varchar(255),
    likecount int,
    videoLink varchar(500),
    writer varchar(250),
    content varchar(500),
    hashtag int,
    primary key(contentId)
    };